# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23739608dbef621ac27169de47e77b968696ef04148f089c8ef963da6eb419e16ed5ef4b442492b23ee0b7219b4306cca44eece7afe62b91cd00092c3cb26fc7

test:
  secret_key_base: f6efa068e80146fe95fb4d7a1b542f400dbd5b8a4ce18ec1a92ebd65193c445fdaaf55137f1c7b8e3f27e65c3d439b681c41fa0d062ee6a7b5faffafae4b9708

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
